In [1]:
# Install conda (runtime will restart)
!pip install -q condacolab
import condacolab
condacolab.install()

⏬ Downloading https://github.com/jaimergp/miniforge/releases/download/24.11.2-1_colab/Miniforge3-colab-24.11.2-1_colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:12
🔁 Restarting kernel...

In [2]:
# Install bioinformatics tools
!conda install -c bioconda -c conda-forge \
    flye medaka minimap2 samtools bcftools ncbi-amrfinderplus -y

Channels:
 - bioconda
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ | / - \ | / done
Solving environment: \ | / - \ done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - bcftools
    - flye
    - medaka
    - minimap2
    - ncbi-amrfinderplus
    - samtools


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-4.5          |       7_kmp_llvm           8 KB  conda-forge
    bcftools-1.23.1            |       hb2cee57_0         927 KB  bioconda
    blast-2.16.0               |       h66d330f_4       141.4 MB  bioconda
    c-ares-1.34.6              |       hb03c661_0         203 KB  conda-forge
    ca-certificates-2026.2.25  |       hbd8a1cb_0         144 KB  conda-forge
    cached-property-1.5.2      |       hd8ed1ab_1           4 KB  conda-forge
    cached_property-1.5.2      |     pyha770c72_1          11 KB  conda-forge
    certifi-2026.2.25          |     pyhd8ed1ab_0         148 KB  conda-forge
    cloudpickle-3.1.2          |     pyhcf101f3_1          27 KB  conda-forge
    conda-26.1.1               |  py311h38be061_0         1.2 MB  conda-forge
    conda-libmamba-solver-25.11.0|     pyhd8ed1ab_1          56 KB  conda-forge
    cpp-expected-1.3.1         |       h171cf75_0          24 KB  conda-forge
    cpython-3.11.15            |  py311hd8ed1ab_0          47 KB  conda-forge
    curl-8.19.0                |       hcf29cc6_0         187 KB  conda-forge
    entrez-direct-22.4         |       he881be0_0        14.0 MB  bioconda
    filelock-3.25.2            |     pyhd8ed1ab_0          25 KB  conda-forge
    flye-2.9.6                 |  py311h2de2dd3_0        34.8 MB  bioconda
    fmt-12.1.0                 |       hff5e90c_0         193 KB  conda-forge
    fsspec-2026.2.0            |     pyhd8ed1ab_0         145 KB  conda-forge
    gmp-6.3.0                  |       hac33072_2         449 KB  conda-forge
    gmpy2-2.3.0                |  py311h92a432a_1         236 KB  conda-forge
    grpcio-1.78.1              |  py311h3aa0767_0         861 KB  conda-forge
    gsl-2.7                    |       he838d99_0         3.2 MB  conda-forge
    h5py-3.16.0                |nompi_py311h0b2f468_100         1.3 MB  conda-forge
    hdf5-1.14.6                |nompi_h2d575fe_101         3.5 MB  conda-forge
    hmmer-3.4                  |       hb6cb901_4        11.4 MB  bioconda
    htslib-1.23.1              |       h633afcb_0         1.1 MB  bioconda
    importlib-metadata-8.8.0   |     pyhcf101f3_0          34 KB  conda-forge
    intervaltree-3.1.0         |     pyhd8ed1ab_1          27 KB  conda-forge
    jinja2-3.1.6               |     pyhcf101f3_1         118 KB  conda-forge
    k8-1.2                     |       he8db53b_6         7.2 MB  bioconda
    kernel-headers_linux-64-5.14.0|       he073ed8_3         1.3 MB  conda-forge
    keyutils-1.6.3             |       hb9d3cd8_0         131 KB  conda-forge
    krb5-1.22.2                |       ha1258a1_0         1.3 MB  conda-forge
    libabseil-20260107.1       | cxx17_h7b12aa8_0         1.3 MB  conda-forge
    libaec-1.1.5               |       h088129d_0          36 KB  conda-forge
    libarchive-3.8.6           | gpl_hc2c16d8_100         866 KB  conda-forge
    libblas-3.9.0              |31_h59b9bed_openblas          16 KB  conda-forge
    libcblas-3.9.0             |31_he106b2a_openblas          16 KB  conda-forge
    libcurl-8.19.0             |       hcf29cc6_0         456 KB  conda-forge
    libdeflate-1.25            |       h17f619e_0          72 KB  conda-forge
    libedit-3.1.20250104       | pl5321h7949ede_0         132 KB  conda-forge
    libgfortran-14.2.0         |       h69a702a_2          52 KB  conda-forge
    libgfortran-ng-14.2.0      |       h69a702a_2          53 KB  conda-forge
    libgfortran5-14.2.0        |       hf1ad2bd_2         1.4 MB  conda-forge
    libgrpc-1.78.1             |       h1d1128b_0         6.7 MB  conda-forge
    libiconv-1.18              |       h3b78370_2         772 KB  conda-forge
    libidn2-2.3.8              |       hfac485b_1         136 KB  conda-forge
    liblapack-3.9.0            |31_h7ac8fdf_openblas          16 KB  conda-forge
    liblzma-5.8.2              |       hb03c661_0         111 KB  conda-forge
    libmamba-2.5.0             |       hd28c85e_0         2.4 MB  conda-forge
    libmamba-spdlog-2.5.0      |       h12fcf84_0          20 KB  conda-forge
    libmambapy-2.5.0           |  py311hc5d5c7c_0         923 KB  conda-forge
    libnghttp2-1.68.1          |       h877daf1_0         648 KB  conda-forge
    libopenblas-0.3.29         |openmp_hd680484_0         5.6 MB  conda-forge
    libprotobuf-6.33.5         |       h2b00c02_0         3.5 MB  conda-forge
    libre2-11-2025.11.05       |       h0dc7533_1         208 KB  conda-forge
    libsolv-0.7.36             |       h9463b59_0         507 KB  conda-forge
    libtorch-2.10.0            |cpu_generic_hd32bbb9_3        58.8 MB  conda-forge
    libunistring-0.9.10        |       h7f98852_0         1.4 MB  conda-forge
    libuv-1.51.0               |       hb03c661_1         874 KB  conda-forge
    libxml2-2.15.2             |       h031cc0b_0          46 KB  conda-forge
    libxml2-16-2.15.2          |       hf2a90c1_0         544 KB  conda-forge
    llvm-openmp-22.1.2         |       h4922eb0_0         5.8 MB  conda-forge
    mamba-2.5.0                |       h9835478_0         554 KB  conda-forge
    mappy-2.30                 |  py311h384fd50_0         179 KB  bioconda
    markupsafe-3.0.3           |  py311h3778330_1          26 KB  conda-forge
    medaka-2.2.0               |  py311h1d3aea1_0         6.1 MB  bioconda
    minimap2-2.30              |       h577a1d6_0         1.3 MB  bioconda
    mpc-1.4.0                  |       he0a73b1_0          98 KB  conda-forge
    mpfr-4.2.2                 |       he0a73b1_0         713 KB  conda-forge
    mpi-1.0                    |          openmpi           4 KB  conda-forge
    mpmath-1.3.0               |     pyhd8ed1ab_1         429 KB  conda-forge
    msgpack-python-1.1.2       |  py311hdf67eae_1         101 KB  conda-forge
    ncbi-amrfinderplus-4.2.7   |       hf69ffd2_0         1.3 MB  bioconda
    ncbi-vdb-3.4.1             |       hd63eeec_0         8.8 MB  bioconda
    networkx-3.6.1             |     pyhcf101f3_0         1.5 MB  conda-forge
    nlohmann_json-abi-3.12.0   |       h0f90c79_1           4 KB  conda-forge
    nomkl-1.0                  |       h5ca1d4c_0           4 KB  conda-forge
    numpy-2.4.3                |  py311h2e04523_0         8.9 MB  conda-forge
    ont-fast5-api-4.1.3        |     pyhdfd78af_0         2.2 MB  bioconda
    openmpi-4.1.6              |     hc5af2df_101         3.9 MB  conda-forge
    openssl-3.6.1              |       h35e630c_1         3.0 MB  conda-forge
    optree-0.19.0              |  py311hdf67eae_0         469 KB  conda-forge
    orjson-3.11.7              |  py311h7098c77_0         339 KB  conda-forge
    parasail-python-1.3.4      |  py311h6947f6e_6         2.8 MB  bioconda
    pcre2-10.47                |       haa7fec5_0         1.2 MB  conda-forge
    perl-5.32.1                | 7_hd590300_perl5        12.7 MB  conda-forge
    perl-archive-tar-3.04      | pl5321hdfd78af_0          34 KB  bioconda
    perl-carp-1.38             | pl5321hdfd78af_4          17 KB  bioconda
    perl-common-sense-3.75     | pl5321hdfd78af_0          13 KB  bioconda
    perl-compress-raw-bzip2-2.214| pl5321hda65f42_0          54 KB  conda-forge
    perl-compress-raw-zlib-2.214| pl5321h4dac143_0          79 KB  conda-forge
    perl-encode-3.19           | pl5321hec16e2b_1         2.1 MB  bioconda
    perl-exporter-5.72         | pl5321hdfd78af_2          16 KB  bioconda
    perl-exporter-tiny-1.002002| pl5321hdfd78af_0          25 KB  bioconda
    perl-extutils-makemaker-7.70| pl5321hd8ed1ab_0         154 KB  conda-forge
    perl-io-compress-2.216     | pl5321h503566f_0          85 KB  bioconda
    perl-io-zlib-1.15          | pl5321hdfd78af_1          12 KB  bioconda
    perl-json-4.11             | pl5321hdfd78af_0          52 KB  bioconda
    perl-json-xs-4.04          | pl5321h9948957_0          69 KB  bioconda
    perl-list-moreutils-0.430  | pl5321hdfd78af_0          32 KB  bioconda
    perl-list-moreutils-xs-0.430| pl5321h7b50bb2_5          50 KB  bioconda
    perl-parent-0.236          | pl5321hdfd78af_2           8 KB  bioconda
    perl-pathtools-3.75        | pl5321hec16e2b_3          42 KB  bioconda
    perl-scalar-list-utils-1.62| pl5321hec16e2b_1          44 KB  bioconda
    perl-types-serialiser-1.01 | pl5321hdfd78af_0          13 KB  bioconda
    progressbar33-2.4          |     pyhd8ed1ab_1          15 KB  conda-forge
    pyabpoa-1.5.6              |  py311hbd8efe9_0         196 KB  bioconda
    pybind11-3.0.1             |     pyh7a1b43c_0         227 KB  conda-forge
    pybind11-abi-11            |       hc364b38_1          14 KB  conda-forge
    pybind11-global-3.0.1      |     pyhc7ab6ef_0         224 KB  conda-forge
    pysam-0.23.3               |  py311haeb7863_2         3.7 MB  bioconda
    pyspoa-0.3.2               |  py311h93bbee8_1         142 KB  bioconda
    python-edlib-1.3.9.post1   |  py311hf552afe_3          79 KB  bioconda
    pytorch-2.10.0             |cpu_generic_py311_hf96630c_3        23.4 MB  conda-forge
    pyvers-0.2.2               |     pyhcf101f3_0          18 KB  conda-forge
    re2-2025.11.05             |       h5301d42_1          27 KB  conda-forge
    rpsbproc-0.5.0             |       hd6d6fdc_2         6.3 MB  bioconda
    samtools-1.23.1            |       ha83d96e_0         479 KB  bioconda
    simdjson-4.2.4             |       hb700be7_0         288 KB  conda-forge
    six-1.17.0                 |     pyhe01879c_1          18 KB  conda-forge
    sleef-3.9.0                |       ha0421bc_0         1.9 MB  conda-forge
    sortedcontainers-2.4.0     |     pyhd8ed1ab_1          28 KB  conda-forge
    spdlog-1.17.0              |       hab81395_1         192 KB  conda-forge
    sympy-1.14.0               |   pyh2585a3b_106         4.4 MB  conda-forge
    sysroot_linux-64-2.34      |       h087de78_3        38.9 MB  conda-forge
    tar-1.35                   |       h3b78370_0         760 KB  conda-forge
    tensordict-0.11.0          |  py311h97a283f_3         794 KB  conda-forge
    toml-0.10.2                |     pyhcf101f3_3          23 KB  conda-forge
    typing-extensions-4.15.0   |       h396c80c_0          89 KB  conda-forge
    typing_extensions-4.15.0   |     pyhcf101f3_0          50 KB  conda-forge
    wget-1.25.0                |       h653f8fd_1         729 KB  conda-forge
    wurlitzer-3.1.1            |     pyhd8ed1ab_1          14 KB  conda-forge
    zipp-3.23.0                |     pyhcf101f3_1          24 KB  conda-forge
    zlib-1.3.1                 |       hb9d3cd8_2          90 KB  conda-forge
    zstandard-0.25.0           |  py311haee01d2_1         456 KB  conda-forge
    zstd-1.5.7                 |       hb78ec9c_6         587 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       462.5 MB

The following NEW packages will be INSTALLED:

  bcftools           bioconda/linux-64::bcftools-1.23.1-hb2cee57_0
  blast              bioconda/linux-64::blast-2.16.0-h66d330f_4
  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
  cloudpickle        conda-forge/noarch::cloudpickle-3.1.2-pyhcf101f3_1
  cpp-expected       conda-forge/linux-64::cpp-expected-1.3.1-h171cf75_0
  cpython            conda-forge/noarch::cpython-3.11.15-py311hd8ed1ab_0
  curl               conda-forge/linux-64::curl-8.19.0-hcf29cc6_0
  entrez-direct      bioconda/linux-64::entrez-direct-22.4-he881be0_0
  filelock           conda-forge/noarch::filelock-3.25.2-pyhd8ed1ab_0
  flye               bioconda/linux-64::flye-2.9.6-py311h2de2dd3_0
  fsspec             conda-forge/noarch::fsspec-2026.2.0-pyhd8ed1ab_0
  gmp                conda-forge/linux-64::gmp-6.3.0-hac33072_2
  gmpy2              conda-forge/linux-64::gmpy2-2.3.0-py311h92a432a_1
  grpcio             conda-forge/linux-64::grpcio-1.78.1-py311h3aa0767_0
  gsl                conda-forge/linux-64::gsl-2.7-he838d99_0
  h5py               conda-forge/linux-64::h5py-3.16.0-nompi_py311h0b2f468_100
  hdf5               conda-forge/linux-64::hdf5-1.14.6-nompi_h2d575fe_101
  hmmer              bioconda/linux-64::hmmer-3.4-hb6cb901_4
  htslib             bioconda/linux-64::htslib-1.23.1-h633afcb_0
  importlib-metadata conda-forge/noarch::importlib-metadata-8.8.0-pyhcf101f3_0
  intervaltree       conda-forge/noarch::intervaltree-3.1.0-pyhd8ed1ab_1
  jinja2             conda-forge/noarch::jinja2-3.1.6-pyhcf101f3_1
  k8                 bioconda/linux-64::k8-1.2-he8db53b_6
  kernel-headers_li~ conda-forge/noarch::kernel-headers_linux-64-5.14.0-he073ed8_3
  libabseil          conda-forge/linux-64::libabseil-20260107.1-cxx17_h7b12aa8_0
  libaec             conda-forge/linux-64::libaec-1.1.5-h088129d_0
  libblas            conda-forge/linux-64::libblas-3.9.0-31_h59b9bed_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-31_he106b2a_openblas
  libdeflate         conda-forge/linux-64::libdeflate-1.25-h17f619e_0
  libgfortran        conda-forge/linux-64::libgfortran-14.2.0-h69a702a_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-14.2.0-h69a702a_2
  libgfortran5       conda-forge/linux-64::libgfortran5-14.2.0-hf1ad2bd_2
  libgrpc            conda-forge/linux-64::libgrpc-1.78.1-h1d1128b_0
  libidn2            conda-forge/linux-64::libidn2-2.3.8-hfac485b_1
  liblapack          conda-forge/linux-64::liblapack-3.9.0-31_h7ac8fdf_openblas
  libmamba-spdlog    conda-forge/linux-64::libmamba-spdlog-2.5.0-h12fcf84_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.29-openmp_hd680484_0
  libprotobuf        conda-forge/linux-64::libprotobuf-6.33.5-h2b00c02_0
  libre2-11          conda-forge/linux-64::libre2-11-2025.11.05-h0dc7533_1
  libtorch           conda-forge/linux-64::libtorch-2.10.0-cpu_generic_hd32bbb9_3
  libunistring       conda-forge/linux-64::libunistring-0.9.10-h7f98852_0
  libuv              conda-forge/linux-64::libuv-1.51.0-hb03c661_1
  libxml2-16         conda-forge/linux-64::libxml2-16-2.15.2-hf2a90c1_0
  llvm-openmp        conda-forge/linux-64::llvm-openmp-22.1.2-h4922eb0_0
  mappy              bioconda/linux-64::mappy-2.30-py311h384fd50_0
  markupsafe         conda-forge/linux-64::markupsafe-3.0.3-py311h3778330_1
  medaka             bioconda/linux-64::medaka-2.2.0-py311h1d3aea1_0
  minimap2           bioconda/linux-64::minimap2-2.30-h577a1d6_0
  mpc                conda-forge/linux-64::mpc-1.4.0-he0a73b1_0
  mpfr               conda-forge/linux-64::mpfr-4.2.2-he0a73b1_0
  mpi                conda-forge/linux-64::mpi-1.0-openmpi
  mpmath             conda-forge/noarch::mpmath-1.3.0-pyhd8ed1ab_1
  msgpack-python     conda-forge/linux-64::msgpack-python-1.1.2-py311hdf67eae_1
  ncbi-amrfinderplus bioconda/linux-64::ncbi-amrfinderplus-4.2.7-hf69ffd2_0
  ncbi-vdb           bioconda/linux-64::ncbi-vdb-3.4.1-hd63eeec_0
  networkx           conda-forge/noarch::networkx-3.6.1-pyhcf101f3_0
  nlohmann_json-abi  conda-forge/noarch::nlohmann_json-abi-3.12.0-h0f90c79_1
  nomkl              conda-forge/noarch::nomkl-1.0-h5ca1d4c_0
  numpy              conda-forge/linux-64::numpy-2.4.3-py311h2e04523_0
  ont-fast5-api      bioconda/noarch::ont-fast5-api-4.1.3-pyhdfd78af_0
  openmpi            conda-forge/linux-64::openmpi-4.1.6-hc5af2df_101
  optree             conda-forge/linux-64::optree-0.19.0-py311hdf67eae_0
  orjson             conda-forge/linux-64::orjson-3.11.7-py311h7098c77_0
  parasail-python    bioconda/linux-64::parasail-python-1.3.4-py311h6947f6e_6
  pcre2              conda-forge/linux-64::pcre2-10.47-haa7fec5_0
  perl               conda-forge/linux-64::perl-5.32.1-7_hd590300_perl5
  perl-archive-tar   bioconda/noarch::perl-archive-tar-3.04-pl5321hdfd78af_0
  perl-carp          bioconda/noarch::perl-carp-1.38-pl5321hdfd78af_4
  perl-common-sense  bioconda/noarch::perl-common-sense-3.75-pl5321hdfd78af_0
  perl-compress-raw~ conda-forge/linux-64::perl-compress-raw-bzip2-2.214-pl5321hda65f42_0
  perl-compress-raw~ conda-forge/linux-64::perl-compress-raw-zlib-2.214-pl5321h4dac143_0
  perl-encode        bioconda/linux-64::perl-encode-3.19-pl5321hec16e2b_1
  perl-exporter      bioconda/noarch::perl-exporter-5.72-pl5321hdfd78af_2
  perl-exporter-tiny bioconda/noarch::perl-exporter-tiny-1.002002-pl5321hdfd78af_0
  perl-extutils-mak~ conda-forge/noarch::perl-extutils-makemaker-7.70-pl5321hd8ed1ab_0
  perl-io-compress   bioconda/linux-64::perl-io-compress-2.216-pl5321h503566f_0
  perl-io-zlib       bioconda/noarch::perl-io-zlib-1.15-pl5321hdfd78af_1
  perl-json          bioconda/noarch::perl-json-4.11-pl5321hdfd78af_0
  perl-json-xs       bioconda/linux-64::perl-json-xs-4.04-pl5321h9948957_0
  perl-list-moreuti~ bioconda/noarch::perl-list-moreutils-0.430-pl5321hdfd78af_0
  perl-list-moreuti~ bioconda/linux-64::perl-list-moreutils-xs-0.430-pl5321h7b50bb2_5
  perl-parent        bioconda/noarch::perl-parent-0.236-pl5321hdfd78af_2
  perl-pathtools     bioconda/linux-64::perl-pathtools-3.75-pl5321hec16e2b_3
  perl-scalar-list-~ bioconda/linux-64::perl-scalar-list-utils-1.62-pl5321hec16e2b_1
  perl-types-serial~ bioconda/noarch::perl-types-serialiser-1.01-pl5321hdfd78af_0
  progressbar33      conda-forge/noarch::progressbar33-2.4-pyhd8ed1ab_1
  pyabpoa            bioconda/linux-64::pyabpoa-1.5.6-py311hbd8efe9_0
  pybind11           conda-forge/noarch::pybind11-3.0.1-pyh7a1b43c_0
  pybind11-global    conda-forge/noarch::pybind11-global-3.0.1-pyhc7ab6ef_0
  pysam              bioconda/linux-64::pysam-0.23.3-py311haeb7863_2
  pyspoa             bioconda/linux-64::pyspoa-0.3.2-py311h93bbee8_1
  python-edlib       bioconda/linux-64::python-edlib-1.3.9.post1-py311hf552afe_3
  pytorch            conda-forge/linux-64::pytorch-2.10.0-cpu_generic_py311_hf96630c_3
  pyvers             conda-forge/noarch::pyvers-0.2.2-pyhcf101f3_0
  re2                conda-forge/linux-64::re2-2025.11.05-h5301d42_1
  rpsbproc           bioconda/linux-64::rpsbproc-0.5.0-hd6d6fdc_2
  samtools           bioconda/linux-64::samtools-1.23.1-ha83d96e_0
  simdjson           conda-forge/linux-64::simdjson-4.2.4-hb700be7_0
  six                conda-forge/noarch::six-1.17.0-pyhe01879c_1
  sleef              conda-forge/linux-64::sleef-3.9.0-ha0421bc_0
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.4.0-pyhd8ed1ab_1
  spdlog             conda-forge/linux-64::spdlog-1.17.0-hab81395_1
  sympy              conda-forge/noarch::sympy-1.14.0-pyh2585a3b_106
  sysroot_linux-64   conda-forge/noarch::sysroot_linux-64-2.34-h087de78_3
  tar                conda-forge/linux-64::tar-1.35-h3b78370_0
  tensordict         conda-forge/linux-64::tensordict-0.11.0-py311h97a283f_3
  toml               conda-forge/noarch::toml-0.10.2-pyhcf101f3_3
  typing-extensions  conda-forge/noarch::typing-extensions-4.15.0-h396c80c_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.15.0-pyhcf101f3_0
  wget               conda-forge/linux-64::wget-1.25.0-h653f8fd_1
  wurlitzer          conda-forge/noarch::wurlitzer-3.1.1-pyhd8ed1ab_1
  zipp               conda-forge/noarch::zipp-3.23.0-pyhcf101f3_1
  zlib               conda-forge/linux-64::zlib-1.3.1-hb9d3cd8_2

The following packages will be UPDATED:

  c-ares                                  1.34.4-hb9d3cd8_0 --> 1.34.6-hb03c661_0
  ca-certificates    conda-forge/linux-64::ca-certificates~ --> conda-forge/noarch::ca-certificates-2026.2.25-hbd8a1cb_0
  certifi                           2024.12.14-pyhd8ed1ab_0 --> 2026.2.25-pyhd8ed1ab_0

In [3]:
!flye --version
!medaka --version
!amrfinder --version

2.9.6-b1802
medaka 2.2.0
4.2.7

In [4]:
from google.colab import files
uploaded = files.upload()

Saving barcode01.fastq.gz to barcode01.fastq.gz
Saving barcode24.fastq.gz to barcode24.fastq.gz
Saving barcode23.fastq.gz to barcode23.fastq.gz
Saving barcode22.fastq.gz to barcode22.fastq.gz
Saving barcode21.fastq.gz to barcode21.fastq.gz
Saving barcode20.fastq.gz to barcode20.fastq.gz
Saving barcode19.fastq.gz to barcode19.fastq.gz
Saving barcode18.fastq.gz to barcode18.fastq.gz
Saving barcode17.fastq.gz to barcode17.fastq.gz
Saving barcode16.fastq.gz to barcode16.fastq.gz
Saving barcode15.fastq.gz to barcode15.fastq.gz
Saving barcode14.fastq.gz to barcode14.fastq.gz
Saving barcode13.fastq.gz to barcode13.fastq.gz
Saving barcode12.fastq.gz to barcode12.fastq.gz
Saving barcode11.fastq.gz to barcode11.fastq.gz
Saving barcode10.fastq.gz to barcode10.fastq.gz
Saving barcode09.fastq.gz to barcode09.fastq.gz
Saving barcode08.fastq.gz to barcode08.fastq.gz
Saving barcode07.fastq.gz to barcode07.fastq.gz
Saving barcode05.fastq.gz to barcode05.fastq.gz
Saving barcode04.fastq.gz to barcode04.fastq.gz
Saving barcode03.fastq.gz to barcode03.fastq.gz
Saving barcode02.fastq.gz to barcode02.fastq.gz

In [6]:
!mkdir -p /content/results

In [1]:
!flye --nano-raw /content/barcode07.fastq.gz \
      --out-dir /content/results/flye_barcode07 \
      --meta --threads 2

[2026-03-27 18:49:36] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 18:49:36] INFO: >>>STAGE: configure
[2026-03-27 18:49:36] INFO: Configuring run
[2026-03-27 18:49:36] INFO: Total read length: 328485
[2026-03-27 18:49:36] INFO: Reads N50/N90: 3249 / 2418
[2026-03-27 18:49:36] INFO: Minimum overlap set to 2000
[2026-03-27 18:49:36] INFO: >>>STAGE: assembly
[2026-03-27 18:49:36] INFO: Assembling disjointigs
[2026-03-27 18:49:36] INFO: Reading sequences
[2026-03-27 18:49:48] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 18:51:16] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 18:51:16] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 18:51:18] INFO: Extending reads
[2026-03-27 18:51:18] INFO: Overlap-based coverage: 2
[2026-03-27 18:51:18] INFO: Median overlap divergence: 0.0340652
0% 10% 20% 40% 70% 100%
[2026-03-27 18:51:19] INFO: Assembled 5 disjointigs
[2026-03-27 18:51:19] INFO: Generating sequence
[2026-03-27 18:51:19] INFO: Filtering contained disjointigs
0% 20% 40% 60% 80% 100%
[2026-03-27 18:51:19] INFO: Contained seqs: 0
[2026-03-27 18:51:19] INFO: >>>STAGE: consensus
[2026-03-27 18:51:19] INFO: Running Minimap2
[2026-03-27 18:51:19] INFO: Computing consensus
[2026-03-27 18:51:19] INFO: Alignment error rate: 0.014914
[2026-03-27 18:51:19] INFO: >>>STAGE: repeat
[2026-03-27 18:51:19] INFO: Building and resolving repeat graph
[2026-03-27 18:51:19] INFO: Parsing disjointigs
[2026-03-27 18:51:19] INFO: Building repeat graph
0% 20% 40% 60% 80% 100%
[2026-03-27 18:51:20] INFO: Median overlap divergence: 0
[2026-03-27 18:51:20] INFO: Parsing reads
[2026-03-27 18:51:20] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 18:51:20] INFO: Aligned read sequence: 46445 / 305411 (0.152074)
[2026-03-27 18:51:20] INFO: Median overlap divergence: 0.0109317
[2026-03-27 18:51:20] INFO: Mean edge coverage: 3
[2026-03-27 18:51:20] INFO: Simplifying the graph
[2026-03-27 18:51:20] INFO: >>>STAGE: contigger
[2026-03-27 18:51:20] INFO: Generating contigs
[2026-03-27 18:51:20] INFO: Reading sequences
[2026-03-27 18:51:20] INFO: Generated 2 contigs
[2026-03-27 18:51:20] INFO: Added 0 scaffold connections
[2026-03-27 18:51:20] INFO: >>>STAGE: polishing
[2026-03-27 18:51:20] INFO: Polishing genome (1/1)
[2026-03-27 18:51:20] INFO: Running minimap2
[2026-03-27 18:51:20] INFO: Separating alignment into bubbles
[2026-03-27 18:51:20] INFO: Alignment error rate: 0.025266
[2026-03-27 18:51:20] INFO: Correcting bubbles
20% 40% 70% 100%
[2026-03-27 18:51:20] INFO: >>>STAGE: finalize
[2026-03-27 18:51:20] INFO: Assembly statistics:

	Total length:	5583
	Fragments:	2
	Fragments N50:	2860
	Largest frg:	2860
	Scaffolds:	0
	Mean coverage:	7

[2026-03-27 18:51:20] INFO: Final assembly: /content/results/flye_barcode07/assembly.fasta

In [3]:
import glob
import os
import shutil

# створюємо папки
os.makedirs("/content/results", exist_ok=True)
os.makedirs("/content/assemblies", exist_ok=True)

fastq_files = sorted(glob.glob("/content/barcode*.fastq.gz"))

for f in fastq_files:
    bc = f.split("barcode")[-1].replace(".fastq.gz", "")

    flye_out = f"/content/results/flye_barcode{bc}"
    assembly_file = f"{flye_out}/assembly.fasta"
    final_out = f"/content/assemblies/barcode{bc}_assembly.fasta"

    print(f"\n===== barcode{bc} =====")

    # 🔹 запускаємо Flye тільки якщо ще не було
    if not os.path.exists(assembly_file):
        print("Running Flye...")

        !flye --nano-raw {f} \
              --out-dir {flye_out} \
              --meta --threads 2
    else:
        print("Already assembled")

    # 🔹 копіюємо в одну папку
    if os.path.exists(assembly_file):
        shutil.copy(assembly_file, final_out)
        print(f"Saved → {final_out}")
    else:
        print("Assembly missing ❌")

===== barcode01 =====
Running Flye...
[2026-03-27 19:59:11] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 19:59:11] INFO: >>>STAGE: configure
[2026-03-27 19:59:11] INFO: Configuring run
[2026-03-27 19:59:11] INFO: Total read length: 12350
[2026-03-27 19:59:11] INFO: Reads N50/N90: 1839 / 1143
[2026-03-27 19:59:11] INFO: Minimum overlap set to 1000
[2026-03-27 19:59:11] INFO: >>>STAGE: assembly
[2026-03-27 19:59:11] INFO: Assembling disjointigs
[2026-03-27 19:59:11] INFO: Reading sequences
[2026-03-27 19:59:33] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:01:03] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:01:03] INFO: Filling index table (2/2)
0% 10% 20% 40% % 30% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:01:04] WARNING: No overlaps found - unable to estimate parameters
[2026-03-27 20:01:04] INFO: Extending reads
[2026-03-27 20:01:04] WARNING: No overlaps found!
[2026-03-27 20:01:04] INFO: Overlap-based coverage: 0
[2026-03-27 20:01:04] INFO: Median overlap divergence: 0
0% 100%
[2026-03-27 20:01:04] INFO: Assembled 0 disjointigs
[2026-03-27 20:01:04] INFO: Generating sequence
[2026-03-27 20:01:04] INFO: Filtering contained disjointigs
[2026-03-27 20:01:04] INFO: Contained seqs: 0
[2026-03-27 20:01:04] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2026-03-27 20:01:04] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode02 =====
Running Flye...
[2026-03-27 20:01:05] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:01:05] INFO: >>>STAGE: configure
[2026-03-27 20:01:05] INFO: Configuring run
[2026-03-27 20:01:05] INFO: Total read length: 21457
[2026-03-27 20:01:05] INFO: Reads N50/N90: 2811 / 2132
[2026-03-27 20:01:05] INFO: Minimum overlap set to 2000
[2026-03-27 20:01:05] INFO: >>>STAGE: assembly
[2026-03-27 20:01:05] INFO: Assembling disjointigs
[2026-03-27 20:01:05] INFO: Reading sequences
[2026-03-27 20:01:10] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:02:40] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:02:40] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:02:41] WARNING: No overlaps found - unable to estimate parameters
[2026-03-27 20:02:41] INFO: Extending reads
[2026-03-27 20:02:41] WARNING: No overlaps found!
[2026-03-27 20:02:41] INFO: Overlap-based coverage: 0
[2026-03-27 20:02:41] INFO: Median overlap divergence: 0
0% 100%
[2026-03-27 20:02:41] INFO: Assembled 0 disjointigs
[2026-03-27 20:02:41] INFO: Generating sequence
[2026-03-27 20:02:42] INFO: Filtering contained disjointigs
[2026-03-27 20:02:42] INFO: Contained seqs: 0
[2026-03-27 20:02:42] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2026-03-27 20:02:42] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode03 =====
Running Flye...
[2026-03-27 20:02:42] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:02:42] INFO: >>>STAGE: configure
[2026-03-27 20:02:42] INFO: Configuring run
[2026-03-27 20:02:42] INFO: Total read length: 108565
[2026-03-27 20:02:42] INFO: Reads N50/N90: 2143 / 1523
[2026-03-27 20:02:42] INFO: Minimum overlap set to 2000
[2026-03-27 20:02:42] INFO: >>>STAGE: assembly
[2026-03-27 20:02:42] INFO: Assembling disjointigs
[2026-03-27 20:02:42] INFO: Reading sequences
[2026-03-27 20:02:47] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:04:15] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:04:15] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:04:18] INFO: Extending reads
[2026-03-27 20:04:18] INFO: Overlap-based coverage: 1
[2026-03-27 20:04:18] INFO: Median overlap divergence: 0.0270398
0% 50% 100%
[2026-03-27 20:04:18] INFO: Assembled 1 disjointigs
[2026-03-27 20:04:18] INFO: Generating sequence
[2026-03-27 20:04:18] INFO: Filtering contained disjointigs
0% 100%
[2026-03-27 20:04:18] INFO: Contained seqs: 0
[2026-03-27 20:04:18] INFO: >>>STAGE: consensus
[2026-03-27 20:04:18] INFO: Running Minimap2
[2026-03-27 20:04:18] INFO: Computing consensus
[2026-03-27 20:04:18] INFO: Alignment error rate: 0.038441
[2026-03-27 20:04:18] INFO: >>>STAGE: repeat
[2026-03-27 20:04:18] INFO: Building and resolving repeat graph
[2026-03-27 20:04:18] INFO: Parsing disjointigs
[2026-03-27 20:04:18] INFO: Building repeat graph
0% 100%
[2026-03-27 20:04:18] INFO: Median overlap divergence: 0
[2026-03-27 20:04:18] INFO: Parsing reads
[2026-03-27 20:04:18] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:04:18] INFO: Aligned read sequence: 4365 / 62728 (0.0695862)
[2026-03-27 20:04:18] INFO: Median overlap divergence: 0.0157914
[2026-03-27 20:04:18] INFO: Mean edge coverage: 1
[2026-03-27 20:04:18] INFO: Simplifying the graph
[2026-03-27 20:04:18] INFO: >>>STAGE: contigger
[2026-03-27 20:04:18] INFO: Generating contigs
[2026-03-27 20:04:18] INFO: Reading sequences
[2026-03-27 20:04:18] INFO: Generated 0 contigs
[2026-03-27 20:04:18] INFO: Added 0 scaffold connections
[2026-03-27 20:04:18] ERROR: No contigs were assembled - pipeline stopped
[2026-03-27 20:04:18] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode04 =====
Running Flye...
[2026-03-27 20:04:19] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:04:19] INFO: >>>STAGE: configure
[2026-03-27 20:04:19] INFO: Configuring run
[2026-03-27 20:04:19] INFO: Total read length: 6245
[2026-03-27 20:04:19] INFO: Reads N50/N90: 1597 / 1193
[2026-03-27 20:04:19] INFO: Minimum overlap set to 1000
[2026-03-27 20:04:19] INFO: >>>STAGE: assembly
[2026-03-27 20:04:19] INFO: Assembling disjointigs
[2026-03-27 20:04:19] INFO: Reading sequences
[2026-03-27 20:04:24] INFO: Counting k-mers:
0% 10% 30% 50% 60% 80% 100%
[2026-03-27 20:05:52] INFO: Filling index table (1/2)
0% 10% 30% 50% 60% 80% 100%
[2026-03-27 20:05:52] INFO: Filling index table (2/2)
0% 10% 30% 50% 60% 80% 100%
[2026-03-27 20:05:53] WARNING: No overlaps found - unable to estimate parameters
[2026-03-27 20:05:53] INFO: Extending reads
[2026-03-27 20:05:53] WARNING: No overlaps found!
[2026-03-27 20:05:53] INFO: Overlap-based coverage: 0
[2026-03-27 20:05:53] INFO: Median overlap divergence: 0
0% 100%
[2026-03-27 20:05:53] INFO: Assembled 0 disjointigs
[2026-03-27 20:05:53] INFO: Generating sequence
[2026-03-27 20:05:53] INFO: Filtering contained disjointigs
[2026-03-27 20:05:53] INFO: Contained seqs: 0
[2026-03-27 20:05:53] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2026-03-27 20:05:53] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode05 =====
Running Flye...
[2026-03-27 20:05:53] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:05:53] INFO: >>>STAGE: configure
[2026-03-27 20:05:53] INFO: Configuring run
[2026-03-27 20:05:53] INFO: Total read length: 52546
[2026-03-27 20:05:53] INFO: Reads N50/N90: 29691 / 2293
[2026-03-27 20:05:53] INFO: Minimum overlap set to 2000
[2026-03-27 20:05:53] INFO: >>>STAGE: assembly
[2026-03-27 20:05:53] INFO: Assembling disjointigs
[2026-03-27 20:05:53] INFO: Reading sequences
[2026-03-27 20:05:59] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:07:27] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:07:27] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:07:28] WARNING: No overlaps found - unable to estimate parameters
[2026-03-27 20:07:28] INFO: Extending reads
[2026-03-27 20:07:29] WARNING: No overlaps found!
[2026-03-27 20:07:29] INFO: Overlap-based coverage: 0
[2026-03-27 20:07:29] INFO: Median overlap divergence: 0
0% 100%
[2026-03-27 20:07:29] INFO: Assembled 0 disjointigs
[2026-03-27 20:07:29] INFO: Generating sequence
[2026-03-27 20:07:29] INFO: Filtering contained disjointigs
[2026-03-27 20:07:29] INFO: Contained seqs: 0
[2026-03-27 20:07:29] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2026-03-27 20:07:29] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode07 =====
Already assembled
Saved → /content/assemblies/barcode07_assembly.fasta

===== barcode08 =====
Already assembled
Saved → /content/assemblies/barcode08_assembly.fasta

===== barcode09 =====
Already assembled
Saved → /content/assemblies/barcode09_assembly.fasta

===== barcode10 =====
Running Flye...
[2026-03-27 20:07:29] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:07:29] INFO: >>>STAGE: configure
[2026-03-27 20:07:29] INFO: Configuring run
[2026-03-27 20:07:29] INFO: Total read length: 18173
[2026-03-27 20:07:29] INFO: Reads N50/N90: 2841 / 1884
[2026-03-27 20:07:29] INFO: Minimum overlap set to 2000
[2026-03-27 20:07:29] INFO: >>>STAGE: assembly
[2026-03-27 20:07:29] INFO: Assembling disjointigs
[2026-03-27 20:07:29] INFO: Reading sequences
[2026-03-27 20:07:35] INFO: Counting k-mers:
0% 10% 202030% % 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:09:02] INFO: Filling index table (1/2)
0% 10% 3030% % 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:09:02] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:09:03] WARNING: No overlaps found - unable to estimate parameters
[2026-03-27 20:09:03] INFO: Extending reads
[2026-03-27 20:09:03] WARNING: No overlaps found!
[2026-03-27 20:09:03] INFO: Overlap-based coverage: 0
[2026-03-27 20:09:03] INFO: Median overlap divergence: 0
0% 100%
[2026-03-27 20:09:03] INFO: Assembled 0 disjointigs
[2026-03-27 20:09:03] INFO: Generating sequence
[2026-03-27 20:09:03] INFO: Filtering contained disjointigs
[2026-03-27 20:09:03] INFO: Contained seqs: 0
[2026-03-27 20:09:03] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2026-03-27 20:09:03] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode11 =====
Running Flye...
[2026-03-27 20:09:04] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:09:04] INFO: >>>STAGE: configure
[2026-03-27 20:09:04] INFO: Configuring run
[2026-03-27 20:09:04] INFO: Total read length: 74661
[2026-03-27 20:09:04] INFO: Reads N50/N90: 3174 / 2092
[2026-03-27 20:09:04] INFO: Minimum overlap set to 2000
[2026-03-27 20:09:04] INFO: >>>STAGE: assembly
[2026-03-27 20:09:04] INFO: Assembling disjointigs
[2026-03-27 20:09:04] INFO: Reading sequences
[2026-03-27 20:09:10] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:10:38] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:10:38] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:10:40] INFO: Extending reads
[2026-03-27 20:10:40] INFO: Overlap-based coverage: 1
[2026-03-27 20:10:40] INFO: Median overlap divergence: 0.0166148
0% 50% 100%
[2026-03-27 20:10:40] INFO: Assembled 1 disjointigs
[2026-03-27 20:10:40] INFO: Generating sequence
[2026-03-27 20:10:40] INFO: Filtering contained disjointigs
0% 100%
[2026-03-27 20:10:40] INFO: Contained seqs: 0
[2026-03-27 20:10:40] INFO: >>>STAGE: consensus
[2026-03-27 20:10:40] INFO: Running Minimap2
[2026-03-27 20:10:40] INFO: Computing consensus
[2026-03-27 20:10:40] INFO: Alignment error rate: 0.010817
[2026-03-27 20:10:40] INFO: >>>STAGE: repeat
[2026-03-27 20:10:40] INFO: Building and resolving repeat graph
[2026-03-27 20:10:40] INFO: Parsing disjointigs
[2026-03-27 20:10:40] INFO: Building repeat graph
0% 100%
[2026-03-27 20:10:40] INFO: Median overlap divergence: 0
[2026-03-27 20:10:40] INFO: Parsing reads
[2026-03-27 20:10:40] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:10:40] INFO: Aligned read sequence: 6027 / 70091 (0.0859882)
[2026-03-27 20:10:40] INFO: Median overlap divergence: 0.011891
[2026-03-27 20:10:40] INFO: Mean edge coverage: 1
[2026-03-27 20:10:40] INFO: Simplifying the graph
[2026-03-27 20:10:40] INFO: >>>STAGE: contigger
[2026-03-27 20:10:40] INFO: Generating contigs
[2026-03-27 20:10:40] INFO: Reading sequences
[2026-03-27 20:10:40] INFO: Generated 0 contigs
[2026-03-27 20:10:40] INFO: Added 0 scaffold connections
[2026-03-27 20:10:40] ERROR: No contigs were assembled - pipeline stopped
[2026-03-27 20:10:40] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode12 =====
Running Flye...
[2026-03-27 20:10:41] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:10:41] INFO: >>>STAGE: configure
[2026-03-27 20:10:41] INFO: Configuring run
[2026-03-27 20:10:41] INFO: Total read length: 6065
[2026-03-27 20:10:41] INFO: Reads N50/N90: 3623 / 2442
[2026-03-27 20:10:41] INFO: Minimum overlap set to 2000
[2026-03-27 20:10:41] INFO: >>>STAGE: assembly
[2026-03-27 20:10:41] INFO: Assembling disjointigs
[2026-03-27 20:10:41] INFO: Reading sequences
[2026-03-27 20:10:46] INFO: Counting k-mers:
0% 20% 50% % 70% 100%
[2026-03-27 20:12:14] INFO: Filling index table (1/2)
0% 20% 50% 70% 100%
[2026-03-27 20:12:14] INFO: Filling index table (2/2)
0% 20% 50% 70% 100%
[2026-03-27 20:12:15] WARNING: No overlaps found - unable to estimate parameters
[2026-03-27 20:12:15] INFO: Extending reads
[2026-03-27 20:12:15] WARNING: No overlaps found!
[2026-03-27 20:12:15] INFO: Overlap-based coverage: 0
[2026-03-27 20:12:15] INFO: Median overlap divergence: 0
0% 100%
[2026-03-27 20:12:15] INFO: Assembled 0 disjointigs
[2026-03-27 20:12:15] INFO: Generating sequence
[2026-03-27 20:12:15] INFO: Filtering contained disjointigs
[2026-03-27 20:12:15] INFO: Contained seqs: 0
[2026-03-27 20:12:15] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2026-03-27 20:12:15] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode13 =====
Running Flye...
[2026-03-27 20:12:15] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:12:15] INFO: >>>STAGE: configure
[2026-03-27 20:12:15] INFO: Configuring run
[2026-03-27 20:12:15] INFO: Total read length: 78509
[2026-03-27 20:12:15] INFO: Reads N50/N90: 3426 / 1964
[2026-03-27 20:12:15] INFO: Minimum overlap set to 2000
[2026-03-27 20:12:15] INFO: >>>STAGE: assembly
[2026-03-27 20:12:15] INFO: Assembling disjointigs
[2026-03-27 20:12:15] INFO: Reading sequences
[2026-03-27 20:12:21] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:13:50] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:13:50] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:13:51] WARNING: No overlaps found - unable to estimate parameters
[2026-03-27 20:13:51] INFO: Extending reads
[2026-03-27 20:13:51] WARNING: No overlaps found!
[2026-03-27 20:13:51] INFO: Overlap-based coverage: 0
[2026-03-27 20:13:51] INFO: Median overlap divergence: 0
0% 100%
[2026-03-27 20:13:51] INFO: Assembled 0 disjointigs
[2026-03-27 20:13:51] INFO: Generating sequence
[2026-03-27 20:13:51] INFO: Filtering contained disjointigs
[2026-03-27 20:13:51] INFO: Contained seqs: 0
[2026-03-27 20:13:51] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2026-03-27 20:13:51] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode14 =====
Running Flye...
[2026-03-27 20:13:51] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:13:51] INFO: >>>STAGE: configure
[2026-03-27 20:13:51] INFO: Configuring run
[2026-03-27 20:13:51] INFO: Total read length: 2316
[2026-03-27 20:13:51] INFO: Reads N50/N90: 2316 / 2316
[2026-03-27 20:13:51] INFO: Minimum overlap set to 2000
[2026-03-27 20:13:51] INFO: >>>STAGE: assembly
[2026-03-27 20:13:51] INFO: Assembling disjointigs
[2026-03-27 20:13:51] INFO: Reading sequences
[2026-03-27 20:13:56] INFO: Counting k-mers:
0% 50% 100%
[2026-03-27 20:15:26] INFO: Filling index table (1/2)
0% 50% 100%
[2026-03-27 20:15:26] INFO: Filling index table (2/2)
0% 50% 100%
[2026-03-27 20:15:27] WARNING: No overlaps found - unable to estimate parameters
[2026-03-27 20:15:27] INFO: Extending reads
[2026-03-27 20:15:27] WARNING: No overlaps found!
[2026-03-27 20:15:27] INFO: Overlap-based coverage: 0
[2026-03-27 20:15:27] INFO: Median overlap divergence: 0
0% 100%
[2026-03-27 20:15:27] INFO: Assembled 0 disjointigs
[2026-03-27 20:15:27] INFO: Generating sequence
[2026-03-27 20:15:27] INFO: Filtering contained disjointigs
[2026-03-27 20:15:27] INFO: Contained seqs: 0
[2026-03-27 20:15:27] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2026-03-27 20:15:27] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode15 =====
Running Flye...
[2026-03-27 20:15:27] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:15:27] INFO: >>>STAGE: configure
[2026-03-27 20:15:27] INFO: Configuring run
[2026-03-27 20:15:27] INFO: Total read length: 22521
[2026-03-27 20:15:27] INFO: Reads N50/N90: 3202 / 2009
[2026-03-27 20:15:27] INFO: Minimum overlap set to 2000
[2026-03-27 20:15:27] INFO: >>>STAGE: assembly
[2026-03-27 20:15:27] INFO: Assembling disjointigs
[2026-03-27 20:15:27] INFO: Reading sequences
[2026-03-27 20:15:33] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% % 80% 90% 100%
[2026-03-27 20:17:03] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:17:03] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2026-03-27 20:17:04] INFO: Extending reads
[2026-03-27 20:17:04] INFO: Overlap-based coverage: 1
[2026-03-27 20:17:04] INFO: Median overlap divergence: 0.0178463
0% 100%
[2026-03-27 20:17:04] INFO: Assembled 0 disjointigs
[2026-03-27 20:17:04] INFO: Generating sequence
[2026-03-27 20:17:04] INFO: Filtering contained disjointigs
[2026-03-27 20:17:04] INFO: Contained seqs: 0
[2026-03-27 20:17:04] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2026-03-27 20:17:04] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode16 =====
Running Flye...
[2026-03-27 20:17:04] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:17:04] INFO: >>>STAGE: configure
[2026-03-27 20:17:04] INFO: Configuring run
[2026-03-27 20:17:04] INFO: Total read length: 4279
[2026-03-27 20:17:04] INFO: Reads N50/N90: 2217 / 905
[2026-03-27 20:17:04] INFO: Minimum overlap set to 1000
[2026-03-27 20:17:04] INFO: >>>STAGE: assembly
[2026-03-27 20:17:04] INFO: Assembling disjointigs
[2026-03-27 20:17:04] INFO: Reading sequences
[2026-03-27 20:17:10] INFO: Counting k-mers:
0% 20% 50% 70% 100%
[2026-03-27 20:18:39] INFO: Filling index table (1/2)
0% 20% 50% 70% 100%
[2026-03-27 20:18:39] INFO: Filling index table (2/2)
0% 20% 50% 70% 100%
[2026-03-27 20:18:40] WARNING: No overlaps found - unable to estimate parameters
[2026-03-27 20:18:40] INFO: Extending reads
[2026-03-27 20:18:40] WARNING: No overlaps found!
[2026-03-27 20:18:40] INFO: Overlap-based coverage: 0
[2026-03-27 20:18:40] INFO: Median overlap divergence: 0
0% 100%
[2026-03-27 20:18:40] INFO: Assembled 0 disjointigs
[2026-03-27 20:18:40] INFO: Generating sequence
[2026-03-27 20:18:40] INFO: Filtering contained disjointigs
[2026-03-27 20:18:40] INFO: Contained seqs: 0
[2026-03-27 20:18:40] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2026-03-27 20:18:40] ERROR: Pipeline aborted
Assembly missing ❌

===== barcode17 =====
Running Flye...
[2026-03-27 20:18:40] INFO: Starting Flye 2.9.6-b1802
[2026-03-27 20:18:40] INFO: >>>STAGE: configure
[2026-03-27 20:18:40] INFO: Configuring run
[2026-03-27 20:18:40] INFO: Total read length: 3246
[2026-03-27 20:18:40] INFO: Reads N50/N90: 1875 / 1371
[2026-03-27 20:18:40] INFO: Minimum overlap set to 1000
[2026-03-27 20:18:40] INFO: >>>STAGE: assembly
[2026-03-27 20:18:40] INFO: Assembling disjointigs
[2026-03-27 20:18:40] INFO: Reading sequences
[2026-03-27 20:18:45] INFO: Counting k-mers:
0% 20% 50% 70% 100%

Medaka

In [4]:
import glob
import os
import shutil

os.makedirs("/content/medaka", exist_ok=True)

assembly_files = glob.glob("/content/assemblies/barcode*_assembly.fasta")

for f in assembly_files:
    bc = f.split("barcode")[-1].replace("_assembly.fasta", "")

    fastq = f"/content/barcode{bc}.fastq.gz"
    medaka_out = f"/content/results/medaka_barcode{bc}"
    consensus_file = f"{medaka_out}/consensus.fasta"
    final_out = f"/content/medaka/barcode{bc}_consensus.fasta"

    print(f"\n===== barcode{bc} =====")

    # 🔹 запускаємо Medaka
    if not os.path.exists(consensus_file):
        print("Running Medaka...")

        !medaka_consensus -i {fastq} -d {f} -o {medaka_out} -t 2
    else:
        print("Already polished")

    # 🔹 копіюємо в одну папку
    if os.path.exists(consensus_file):
        shutil.copy(consensus_file, final_out)
        print(f"Saved → {final_out}")
    else:
        print("Consensus missing ❌")

===== barcode08 =====
Running Medaka...
Attempting to automatically select model version.
SUCCESS: Automatic model selection chose model: '/usr/local/lib/python3.11/site-packages/medaka/data/r1041_e82_400bps_sup_v5.2.0_model_pt.tar.gz'
Checking program versions
This is medaka 2.2.0
Program    Version    Required   Pass
bcftools   1.23.1     1.11       True
bgzip      1.23.1     1.11       True
minimap2   2.30       2.11       True
samtools   1.23.1     1.11       True
tabix      1.23.1     1.11       True
[20:33:57 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmpqo0wr28k.
[20:34:01 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmpin1xeiwp.
[20:34:06 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmpfaii4htf.
[20:34:06 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmp8lmt5kfk.
Aligning basecalls to draft
Creating fai index file /content/assemblies/barcode08_assembly.fasta.fai
Creating mmi index file /content/assemblies/barcode08_assembly.fasta.map-ont.mmi
[M::mm_idx_gen::0.003*1.33] collected minimizers
[M::mm_idx_gen::0.004*1.24] sorted minimizers
[M::main::0.007*1.00] loaded/built the index for 5 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 5
[M::mm_idx_stat::0.007*0.99] distinct minimizers: 2421 (99.63% are singletons); average occurrences: 1.014; average spacing: 5.426; total length: 13320
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -I 16G -x map-ont -d /content/assemblies/barcode08_assembly.fasta.map-ont.mmi /content/assemblies/barcode08_assembly.fasta
[M::main] Real time: 0.008 sec; CPU: 0.008 sec; Peak RSS: 0.004 GB
[M::main::0.005*1.10] loaded/built the index for 5 target sequence(s)
[M::mm_mapopt_update::0.006*1.09] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 5
[M::mm_idx_stat::0.006*1.08] distinct minimizers: 2421 (99.63% are singletons); average occurrences: 1.014; average spacing: 5.426; total length: 13320
[M::worker_pipeline::1.439*1.04] mapped 433 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x map-ont --secondary=no -L --MD -A 2 -B 4 -O 4,24 -E 2,1 -t 2 -a /content/assemblies/barcode08_assembly.fasta.map-ont.mmi /content/barcode08.fastq.gz
[M::main] Real time: 1.448 sec; CPU: 1.504 sec; Peak RSS: 0.076 GB
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
Running medaka inference
[20:34:12 - Predict] Setting pytorch intra/inter-op threads to 2/1.
[20:34:12 - Predict] PyTorch reports intra/inter-op threads as 2/1.
[20:34:12 - Predict] Processing region(s): contig_1:0-2981 contig_2:0-2326 contig_3:0-2594 contig_4:0-2601 contig_5:0-2818
[20:34:12 - Predict] Using model: /usr/local/lib/python3.11/site-packages/medaka/data/r1041_e82_400bps_sup_v5.2.0_model_pt.tar.gz.
[20:34:12 - Predict] Using minimum mapQ threshold of 1 for read filtering.
[20:34:12 - MdlStrTGZ] Model GRUModel(
  (gru): GRU(10, 128, num_layers=2, batch_first=True, bidirectional=True)
  (linear): Linear(in_features=256, out_features=5, bias=True)
)
[20:34:12 - MdlStrTGZ] loading weights from /tmp/tmpemtd50ac/model/weights.pt
[20:34:12 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmpemtd50ac.
[20:34:12 - Predict] Model device: cpu
[20:34:12 - Predict] Running prediction at full precision
[20:34:12 - Predict] Processing 5 short region(s).
[20:34:12 - PWorker] Running inference for 0.0M draft bases.
[20:34:16 - PWorker] Processed 5 batches
[20:34:16 - PWorker] All done, 0 remainder regions.
[20:34:16 - Predict] Finished processing all regions.
[20:34:21 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:34:21 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:34:21 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:34:21 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:34:21 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:34:21 - DataIndx] Loaded 1/1 (100.00%) sample files.
Polished assembly written to /content/results/medaka_barcode08/consensus.fasta, have a nice day.
Saved → /content/medaka/barcode08_consensus.fasta

===== barcode07 =====
Running Medaka...
Attempting to automatically select model version.
SUCCESS: Automatic model selection chose model: '/usr/local/lib/python3.11/site-packages/medaka/data/r1041_e82_400bps_sup_v5.2.0_model_pt.tar.gz'
Checking program versions
This is medaka 2.2.0
Program    Version    Required   Pass
bcftools   1.23.1     1.11       True
bgzip      1.23.1     1.11       True
minimap2   2.30       2.11       True
samtools   1.23.1     1.11       True
tabix      1.23.1     1.11       True
[20:34:41 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmp47gjf68l.
[20:34:45 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmpdgc8hm6s.
[20:34:51 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmpm3vv0kbm.
[20:34:51 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmp3m72rro0.
Aligning basecalls to draft
Creating fai index file /content/assemblies/barcode07_assembly.fasta.fai
Creating mmi index file /content/assemblies/barcode07_assembly.fasta.map-ont.mmi
[M::mm_idx_gen::0.002*1.64] collected minimizers
[M::mm_idx_gen::0.003*1.48] sorted minimizers
[M::main::0.004*1.28] loaded/built the index for 2 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2
[M::mm_idx_stat::0.004*1.27] distinct minimizers: 1062 (99.44% are singletons); average occurrences: 1.006; average spacing: 5.228; total length: 5583
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -I 16G -x map-ont -d /content/assemblies/barcode07_assembly.fasta.map-ont.mmi /content/assemblies/barcode07_assembly.fasta
[M::main] Real time: 0.005 sec; CPU: 0.006 sec; Peak RSS: 0.003 GB
[M::main::0.003*1.48] loaded/built the index for 2 target sequence(s)
[M::mm_mapopt_update::0.004*1.44] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2
[M::mm_idx_stat::0.004*1.42] distinct minimizers: 1062 (99.44% are singletons); average occurrences: 1.006; average spacing: 5.228; total length: 5583
[M::worker_pipeline::0.075*1.54] mapped 109 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x map-ont --secondary=no -L --MD -A 2 -B 4 -O 4,24 -E 2,1 -t 2 -a /content/assemblies/barcode07_assembly.fasta.map-ont.mmi /content/barcode07.fastq.gz
[M::main] Real time: 0.076 sec; CPU: 0.117 sec; Peak RSS: 0.025 GB
Running medaka inference
[20:34:55 - Predict] Setting pytorch intra/inter-op threads to 2/1.
[20:34:55 - Predict] PyTorch reports intra/inter-op threads as 2/1.
[20:34:55 - Predict] Processing region(s): contig_1:0-2723 contig_2:0-2860
[20:34:55 - Predict] Using model: /usr/local/lib/python3.11/site-packages/medaka/data/r1041_e82_400bps_sup_v5.2.0_model_pt.tar.gz.
[20:34:55 - Predict] Using minimum mapQ threshold of 1 for read filtering.
[20:34:55 - MdlStrTGZ] Model GRUModel(
  (gru): GRU(10, 128, num_layers=2, batch_first=True, bidirectional=True)
  (linear): Linear(in_features=256, out_features=5, bias=True)
)
[20:34:55 - MdlStrTGZ] loading weights from /tmp/tmppxs9ujwl/model/weights.pt
[20:34:55 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmppxs9ujwl.
[20:34:55 - Predict] Model device: cpu
[20:34:55 - Predict] Running prediction at full precision
[20:34:55 - Predict] Processing 2 short region(s).
[20:34:55 - PWorker] Running inference for 0.0M draft bases.
[20:34:58 - PWorker] Processed 2 batches
[20:34:58 - PWorker] All done, 0 remainder regions.
[20:34:58 - Predict] Finished processing all regions.
[20:35:03 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:03 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:03 - DataIndx] Loaded 1/1 (100.00%) sample files.
Polished assembly written to /content/results/medaka_barcode07/consensus.fasta, have a nice day.
Saved → /content/medaka/barcode07_consensus.fasta

===== barcode09 =====
Running Medaka...
Attempting to automatically select model version.
SUCCESS: Automatic model selection chose model: '/usr/local/lib/python3.11/site-packages/medaka/data/r1041_e82_400bps_sup_v5.2.0_model_pt.tar.gz'
Checking program versions
This is medaka 2.2.0
Program    Version    Required   Pass
bcftools   1.23.1     1.11       True
bgzip      1.23.1     1.11       True
minimap2   2.30       2.11       True
samtools   1.23.1     1.11       True
tabix      1.23.1     1.11       True
[20:35:22 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmpoxxru9b7.
[20:35:27 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmpsuh0qs2a.
[20:35:32 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmpxmg3qpoj.
[20:35:32 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmp525da_8e.
Aligning basecalls to draft
Creating fai index file /content/assemblies/barcode09_assembly.fasta.fai
Creating mmi index file /content/assemblies/barcode09_assembly.fasta.map-ont.mmi
[M::mm_idx_gen::0.003*1.16] collected minimizers
[M::mm_idx_gen::0.005*1.29] sorted minimizers
[M::main::0.008*1.20] loaded/built the index for 10 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 10
[M::mm_idx_stat::0.008*1.19] distinct minimizers: 6079 (92.91% are singletons); average occurrences: 1.086; average spacing: 5.360; total length: 35369
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -I 16G -x map-ont -d /content/assemblies/barcode09_assembly.fasta.map-ont.mmi /content/assemblies/barcode09_assembly.fasta
[M::main] Real time: 0.009 sec; CPU: 0.010 sec; Peak RSS: 0.004 GB
[M::main::0.006*1.27] loaded/built the index for 10 target sequence(s)
[M::mm_mapopt_update::0.006*1.25] mid_occ = 17
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 10
[M::mm_idx_stat::0.007*1.23] distinct minimizers: 6079 (92.91% are singletons); average occurrences: 1.086; average spacing: 5.360; total length: 35369
[M::worker_pipeline::1.301*1.87] mapped 445 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x map-ont --secondary=no -L --MD -A 2 -B 4 -O 4,24 -E 2,1 -t 2 -a /content/assemblies/barcode09_assembly.fasta.map-ont.mmi /content/barcode09.fastq.gz
[M::main] Real time: 1.304 sec; CPU: 2.433 sec; Peak RSS: 0.153 GB
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
Running medaka inference
[20:35:38 - Predict] Setting pytorch intra/inter-op threads to 2/1.
[20:35:38 - Predict] PyTorch reports intra/inter-op threads as 2/1.
[20:35:38 - Predict] Processing region(s): contig_1:0-3519 contig_10:0-2934 contig_2:0-3499 contig_3:0-3358 contig_4:0-2832 contig_5:0-3110 contig_6:0-6462 contig_7:0-3496 contig_8:0-2226 contig_9:0-3933
[20:35:38 - Predict] Using model: /usr/local/lib/python3.11/site-packages/medaka/data/r1041_e82_400bps_sup_v5.2.0_model_pt.tar.gz.
[20:35:38 - Predict] Using minimum mapQ threshold of 1 for read filtering.
[20:35:38 - MdlStrTGZ] Model GRUModel(
  (gru): GRU(10, 128, num_layers=2, batch_first=True, bidirectional=True)
  (linear): Linear(in_features=256, out_features=5, bias=True)
)
[20:35:38 - MdlStrTGZ] loading weights from /tmp/tmpp1j1imby/model/weights.pt
[20:35:38 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmpp1j1imby.
[20:35:38 - Predict] Model device: cpu
[20:35:38 - Predict] Running prediction at full precision
[20:35:38 - Predict] Processing 10 short region(s).
[20:35:38 - PWorker] Running inference for 0.0M draft bases.
[20:35:49 - PWorker] Processed 10 batches
[20:35:49 - PWorker] All done, 0 remainder regions.
[20:35:49 - Predict] Finished processing all regions.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:35:54 - DataIndx] Loaded 1/1 (100.00%) sample files.
Polished assembly written to /content/results/medaka_barcode09/consensus.fasta, have a nice day.
Saved → /content/medaka/barcode09_consensus.fasta

===== barcode18 =====
Running Medaka...
Attempting to automatically select model version.
SUCCESS: Automatic model selection chose model: '/usr/local/lib/python3.11/site-packages/medaka/data/r1041_e82_400bps_sup_v5.2.0_model_pt.tar.gz'
Checking program versions
This is medaka 2.2.0
Program    Version    Required   Pass
bcftools   1.23.1     1.11       True
bgzip      1.23.1     1.11       True
minimap2   2.30       2.11       True
samtools   1.23.1     1.11       True
tabix      1.23.1     1.11       True
[20:36:14 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmp4uop69jc.
[20:36:19 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmp1heiimma.
[20:36:24 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmp5_u0rrzy.
[20:36:24 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmprn9digf0.
Aligning basecalls to draft
Creating fai index file /content/assemblies/barcode18_assembly.fasta.fai
Creating mmi index file /content/assemblies/barcode18_assembly.fasta.map-ont.mmi
[M::mm_idx_gen::0.006*1.14] collected minimizers
[M::mm_idx_gen::0.011*1.46] sorted minimizers
[M::main::0.015*1.35] loaded/built the index for 29 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 29
[M::mm_idx_stat::0.016*1.33] distinct minimizers: 19443 (99.46% are singletons); average occurrences: 1.019; average spacing: 5.363; total length: 106219
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -I 16G -x map-ont -d /content/assemblies/barcode18_assembly.fasta.map-ont.mmi /content/assemblies/barcode18_assembly.fasta
[M::main] Real time: 0.019 sec; CPU: 0.024 sec; Peak RSS: 0.005 GB
[M::main::0.008*1.03] loaded/built the index for 29 target sequence(s)
[M::mm_mapopt_update::0.009*1.03] mid_occ = 32
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 29
[M::mm_idx_stat::0.009*1.03] distinct minimizers: 19443 (99.46% are singletons); average occurrences: 1.019; average spacing: 5.363; total length: 106219
[M::worker_pipeline::2.046*1.83] mapped 1144 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x map-ont --secondary=no -L --MD -A 2 -B 4 -O 4,24 -E 2,1 -t 2 -a /content/assemblies/barcode18_assembly.fasta.map-ont.mmi /content/barcode18.fastq.gz
[M::main] Real time: 2.052 sec; CPU: 3.741 sec; Peak RSS: 0.145 GB
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
Running medaka inference
[20:36:31 - Predict] Setting pytorch intra/inter-op threads to 2/1.
[20:36:31 - Predict] PyTorch reports intra/inter-op threads as 2/1.
[20:36:31 - Predict] Processing region(s): contig_1:0-4831 contig_10:0-3135 contig_11:0-5569 contig_12:0-2346 contig_13:0-4500 contig_14:0-4046 contig_15:0-2319 contig_16:0-2203 contig_17:0-3441 contig_18:0-3214 contig_19:0-5037 contig_2:0-5370 contig_20:0-2811 contig_21:0-3815 contig_22:0-3619 contig_23:0-4257 contig_24:0-2213 contig_25:0-3242 contig_26:0-3940 contig_27:0-2593 contig_28:0-4855 contig_29:0-4068 contig_3:0-4064 contig_4:0-3897 contig_5:0-3813 contig_6:0-3192 contig_7:0-4016 contig_8:0-3261 contig_9:0-2552
[20:36:31 - Predict] Using model: /usr/local/lib/python3.11/site-packages/medaka/data/r1041_e82_400bps_sup_v5.2.0_model_pt.tar.gz.
[20:36:31 - Predict] Using minimum mapQ threshold of 1 for read filtering.
[20:36:31 - MdlStrTGZ] Model GRUModel(
  (gru): GRU(10, 128, num_layers=2, batch_first=True, bidirectional=True)
  (linear): Linear(in_features=256, out_features=5, bias=True)
)
[20:36:31 - MdlStrTGZ] loading weights from /tmp/tmp6novbgkr/model/weights.pt
[20:36:31 - MdlStrTGZ] Successfully removed temporary files from /tmp/tmp6novbgkr.
[20:36:31 - Predict] Model device: cpu
[20:36:31 - Predict] Running prediction at full precision
[20:36:31 - Predict] Processing 29 short region(s).
[20:36:31 - PWorker] Running inference for 0.1M draft bases.
[20:37:06 - PWorker] Processed 29 batches
[20:37:06 - PWorker] All done, 0 remainder regions.
[20:37:06 - Predict] Finished processing all regions.
[20:37:10 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:37:11 - DataIndx] Loaded 1/1 (100.00%) sample files.
Polished assembly written to /content/results/medaka_barcode18/consensus.fasta, have a nice day.
Saved → /content/medaka/barcode18_consensus.fasta

In [7]:
!amrfinder -u

Running: amrfinder -u
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Software directory: /usr/local/bin/
Software version: 4.2.7
WARNING: This was compiled for running under bioconda, but $CONDA_PREFIX was not found
Reverting to hard coded directory: /usr/local/share/amrfinderplus/data/latest
Running: /usr/local/bin/amrfinder_update -d /usr/local/share/amrfinderplus/data
Looking up the published databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
Looking for the target directory: /usr/local/share/amrfinderplus/data/2026-03-24.1/
Downloading AMRFinder database version 2026-03-24.1 into: /usr/local/share/amrfinderplus/data/2026-03-24.1/
Running: /usr/local/bin/amrfinder_index /usr/local/share/amrfinderplus/data/2026-03-24.1/
Indexing
amrfinder_index took 8 seconds to complete
amrfinder_update took 13 seconds to complete
Database directory: /usr/local/share/amrfinderplus/data/2026-03-24.1
Database version: 2026-03-24.1
amrfinder took 13 seconds to complete

In [8]:
import glob
import pandas as pd
import os

# 🔥 ОБОВ'ЯЗКОВО
os.makedirs("/content/amr_results", exist_ok=True)

dfs = []

consensus_files = sorted(glob.glob("/content/medaka/barcode*_consensus.fasta"))

for f in consensus_files:
    bc = f.split("barcode")[-1].replace("_consensus.fasta", "")

    out_file = f"/content/amr_results/barcode{bc}_amr.tsv"

    print(f"\n===== barcode{bc} =====")
    print(f"Using: {f}")

    !amrfinder -n {f} -o {out_file}

    if os.path.exists(out_file):
        df = pd.read_csv(out_file, sep="\t")
        df["barcode"] = f"barcode{bc}"
        dfs.append(df)
        print(f"Found {len(df)} genes")
    else:
        print("No AMR output")

all_amr = pd.concat(dfs) if dfs else pd.DataFrame()

all_amr.head()

===== barcode07 =====
Using: /content/medaka/barcode07_consensus.fasta
Running: amrfinder -n /content/medaka/barcode07_consensus.fasta -o /content/amr_results/barcode07_amr.tsv
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Software directory: /usr/local/bin/
Software version: 4.2.7
WARNING: This was compiled for running under bioconda, but $CONDA_PREFIX was not found
Reverting to hard coded directory: /usr/local/share/amrfinderplus/data/latest
Database directory: /usr/local/share/amrfinderplus/data/2026-03-24.1
Database version: 2026-03-24.1
AMRFinder translated nucleotide search
  - include -O ORGANISM, --organism ORGANISM option to add mutation searches and suppress common proteins
Running blastx
Making report
amrfinder took 0 seconds to complete
Found 1 genes

===== barcode08 =====
Using: /content/medaka/barcode08_consensus.fasta
Running: amrfinder -n /content/medaka/barcode08_consensus.fasta -o /content/amr_results/barcode08_amr.tsv
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Software directory: /usr/local/bin/
Software version: 4.2.7
WARNING: This was compiled for running under bioconda, but $CONDA_PREFIX was not found
Reverting to hard coded directory: /usr/local/share/amrfinderplus/data/latest
Database directory: /usr/local/share/amrfinderplus/data/2026-03-24.1
Database version: 2026-03-24.1
AMRFinder translated nucleotide search
  - include -O ORGANISM, --organism ORGANISM option to add mutation searches and suppress common proteins
Running blastx
Making report
amrfinder took 1 seconds to complete
Found 0 genes

===== barcode09 =====
Using: /content/medaka/barcode09_consensus.fasta
Running: amrfinder -n /content/medaka/barcode09_consensus.fasta -o /content/amr_results/barcode09_amr.tsv
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Software directory: /usr/local/bin/
Software version: 4.2.7
WARNING: This was compiled for running under bioconda, but $CONDA_PREFIX was not found
Reverting to hard coded directory: /usr/local/share/amrfinderplus/data/latest
Database directory: /usr/local/share/amrfinderplus/data/2026-03-24.1
Database version: 2026-03-24.1
AMRFinder translated nucleotide search
  - include -O ORGANISM, --organism ORGANISM option to add mutation searches and suppress common proteins
Running blastx
Making report
amrfinder took 2 seconds to complete
Found 1 genes

===== barcode18 =====
Using: /content/medaka/barcode18_consensus.fasta
Running: amrfinder -n /content/medaka/barcode18_consensus.fasta -o /content/amr_results/barcode18_amr.tsv
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Software directory: /usr/local/bin/
Software version: 4.2.7
WARNING: This was compiled for running under bioconda, but $CONDA_PREFIX was not found
Reverting to hard coded directory: /usr/local/share/amrfinderplus/data/latest
Database directory: /usr/local/share/amrfinderplus/data/2026-03-24.1
Database version: 2026-03-24.1
AMRFinder translated nucleotide search
  - include -O ORGANISM, --organism ORGANISM option to add mutation searches and suppress common proteins
Running blastx
Making report
amrfinder took 3 seconds to complete
Found 1 genes

/tmp/ipykernel_14571/1915393185.py:30: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_amr = pd.concat(dfs) if dfs else pd.DataFrame()

,Protein id,Contig id,Start,Stop,Strand,Element symbol,Element name,Scope,Type,Subtype,...,Target length,Reference sequence length,% Coverage of reference,% Identity to reference,Alignment length,Closest reference accession,Closest reference name,HMM accession,HMM description,barcode
0,NaN,contig_2,1660,2301,-,qnrD1,quinolone resistance pentapeptide repeat prote...,core,AMR,AMR,...,214,214,100.00,100.0,214,WP_012634451.1,quinolone resistance pentapeptide repeat prote...,NaN,NaN,barcode07
0,NaN,contig_4,2146,2682,+,qnrD,QnrD family quinolone resistance pentapeptide ...,core,AMR,AMR,...,179,214,83.64,100.0,179,WP_012634451.1,quinolone resistance pentapeptide repeat prote...,NaN,NaN,barcode09
0,NaN,contig_20,919,1560,+,qnrD1,quinolone resistance pentapeptide repeat prote...,core,AMR,AMR,...,214,214,100.00,100.0,214,WP_012634451.1,quinolone resistance pentapeptide repeat prote...,NaN,NaN,barcode18

In [9]:
# high-risk класи
high_priority = all_amr[
    all_amr["Class"].isin([
        "BETA-LACTAM",     # ESBL
        "CARBAPENEM",      # critical
        "COLISTIN",        # last-resort antibiotic
        "QUINOLONE"
    ])
]

high_priority[["barcode", "Element symbol", "Class"]]

     barcode Element symbol      Class
0  barcode07          qnrD1  QUINOLONE
0  barcode09           qnrD  QUINOLONE
0  barcode18          qnrD1  QUINOLONE

In [10]:
esbl = all_amr[
    all_amr["Element symbol"].str.contains("bla", case=False, na=False)
]

esbl[["barcode", "Element symbol", "Class"]]

Empty DataFrame
Columns: [barcode, Element symbol, Class]
Index: []

In [11]:
all_amr["Class"].value_counts()

Class
QUINOLONE    3
Name: count, dtype: int64

In [16]:
from google.colab import files
uploaded = files.upload()

Saving mob_results.zip to mob_results.zip

In [17]:
!unzip mob_results.zip

Archive:  mob_results.zip
   creating: content/mob_results/
   creating: content/mob_results/barcode09/
  inflating: content/mob_results/barcode09/plasmid_AD087.fasta
  inflating: content/mob_results/barcode09/contig_report.txt
  inflating: content/mob_results/barcode09/chromosome.fasta
  inflating: content/mob_results/barcode09/biomarkers.blast.txt
  inflating: content/mob_results/barcode09/plasmid_AB434.fasta
  inflating: content/mob_results/barcode09/mobtyper_results.txt
   creating: content/mob_results/barcode08/
  inflating: content/mob_results/barcode08/contig_report.txt
  inflating: content/mob_results/barcode08/chromosome.fasta
   creating: content/mob_results/barcode18/
  inflating: content/mob_results/barcode18/contig_report.txt
  inflating: content/mob_results/barcode18/chromosome.fasta
  inflating: content/mob_results/barcode18/biomarkers.blast.txt
  inflating: content/mob_results/barcode18/plasmid_AB434.fasta
  inflating: content/mob_results/barcode18/mobtyper_results.txt
   creating: content/mob_results/barcode07/
  inflating: content/mob_results/barcode07/contig_report.txt
  inflating: content/mob_results/barcode07/chromosome.fasta
  inflating: content/mob_results/barcode07/biomarkers.blast.txt
  inflating: content/mob_results/barcode07/plasmid_AB434.fasta
  inflating: content/mob_results/barcode07/mobtyper_results.txt

In [19]:
!ls content/mob_results

barcode07  barcode08  barcode09  barcode18

In [20]:
import pandas as pd
import glob

mob_dfs = []

files = glob.glob("content/mob_results/barcode*/contig_report.txt")

for f in files:
    bc = f.split("barcode")[-1].split("/")[0]

    df = pd.read_csv(f, sep="\t")
    df["barcode"] = f"barcode{bc}"

    mob_dfs.append(df)

mob_all = pd.concat(mob_dfs)

mob_all

,sample_id,molecule_type,primary_cluster_id,secondary_cluster_id,contig_id,size,gc,md5,circularity_status,rep_type(s),...,orit_type(s),orit_accession(s),predicted_mobility,mash_nearest_neighbor,mash_neighbor_distance,mash_neighbor_identification,repetitive_dna_id,repetitive_dna_type,filtering_reason,barcode
0,barcode09_assembly,chromosome,-,-,contig_1,3499,0.525579,d5ead7dc1a045ac129c087bfdb4aaa95,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode09
1,barcode09_assembly,chromosome,-,-,contig_10,2934,0.473074,c0c75031285646777d12418cab09f0bd,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode09
2,barcode09_assembly,chromosome,-,-,contig_2,3358,0.626266,5bfc41c449ce66258dce36d4b3e8cb9d,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode09
3,barcode09_assembly,chromosome,-,-,contig_3,3519,0.515487,ed3933acc3cb9ceb658a5d43851e6b19,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode09
4,barcode09_assembly,plasmid,AB434,AK211,contig_4,2832,0.423729,d93006217a66ad83d886cd2f1e13eb9e,not tested,Col3M,...,-,-,-,JQ776508,0.00378594,Proteus mirabilis,-,-,-,barcode09
5,barcode09_assembly,chromosome,-,-,contig_5,3110,0.516399,513acffb4909cd58f52653055a058c7b,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode09
6,barcode09_assembly,chromosome,-,-,contig_6,6462,0.630145,2447165ffb0d814baf1db865f6d2a78d,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode09
7,barcode09_assembly,plasmid,AD087,AM516,contig_7,3496,0.548055,735a9214fcd116463bd58846e63175cc,not tested,-,...,-,-,-,CP039608,0.00128842,Salmonella enterica subsp. enterica,-,-,-,barcode09
8,barcode09_assembly,chromosome,-,-,contig_8,2226,0.459119,b542548cbd00da4588a237faa362f99e,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode09
9,barcode09_assembly,chromosome,-,-,contig_9,3933,0.525553,037e5c8f643edd7dcbac4113726edb85,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode09
0,barcode08_assembly,chromosome,-,-,contig_1,2981,0.423683,0caaafcf9dcc30ead8e4495a2be2a878,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode08
1,barcode08_assembly,chromosome,-,-,contig_2,2326,0.417025,5ccba94d3b87ab08c84eb1c7c2959bf6,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode08
2,barcode08_assembly,chromosome,-,-,contig_3,2594,0.529684,b0e2a2820b0eaaed33b6796b4b831989,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode08
3,barcode08_assembly,chromosome,-,-,contig_4,2601,0.558247,c9a81141b8083c593765bbc500de0f0a,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode08
4,barcode08_assembly,chromosome,-,-,contig_5,2818,0.537615,6e8c671817e184244679b5f52aa840f4,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode08
0,barcode18_assembly,chromosome,-,-,contig_1,4831,0.485614,57f3add746f9fea7272f3caa04a249d6,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
1,barcode18_assembly,chromosome,-,-,contig_10,3135,0.525997,c0c45eaa10aa50a44e70d3eb57c83d10,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
2,barcode18_assembly,chromosome,-,-,contig_11,5569,0.521458,e72c3f38debe0b42c62ab2bb5cb0133e,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
3,barcode18_assembly,chromosome,-,-,contig_12,2346,0.514493,5588910ab8089197bb9ea01b81b215e4,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
4,barcode18_assembly,chromosome,-,-,contig_13,4500,0.476667,14cb7ce0d3c09726cd1ac74153f71c30,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
5,barcode18_assembly,chromosome,-,-,contig_14,4046,0.506426,f588496eaf46b51c305dc2cf639e27f4,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
6,barcode18_assembly,chromosome,-,-,contig_15,2319,0.508840,a4e4a1a4aee38425523d10c7ccd983cf,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
7,barcode18_assembly,chromosome,-,-,contig_16,2203,0.563777,4f9594a6bb6dc11c16bd2d45ab9b5007,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
8,barcode18_assembly,chromosome,-,-,contig_17,3441,0.546934,8e7ecee92bc15e12109cec791605bf86,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
9,barcode18_assembly,chromosome,-,-,contig_18,3214,0.476042,91f0adac7558e7c98782ac3f8f48e717,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
10,barcode18_assembly,chromosome,-,-,contig_19,5037,0.476673,d9134dfef38a1809ed5d954c0fe03288,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
11,barcode18_assembly,chromosome,-,-,contig_2,5370,0.559404,f010fdc9aa06f70cdb5472c063eb95e5,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
12,barcode18_assembly,plasmid,AB434,AK211,contig_20,2811,0.420847,b5205e2264a8aabddb9de0d10557995c,not tested,Col3M,...,-,-,-,JQ776508,0.00141786,Proteus mirabilis,-,-,-,barcode18
13,barcode18_assembly,chromosome,-,-,contig_21,3815,0.572215,273ed533b4993f0a84851c7b7901753d,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
14,barcode18_assembly,chromosome,-,-,contig_22,3619,0.376347,24fc59ad315403b73293964c35e841e8,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
15,barcode18_assembly,chromosome,-,-,contig_23,4257,0.533709,8deea61557a86236c2810c28fdfb4719,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
16,barcode18_assembly,chromosome,-,-,contig_24,2213,0.491188,525decb95ffefd44e44bb04bf8327f3f,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
17,barcode18_assembly,chromosome,-,-,contig_25,3242,0.505552,95214565044b5489180241afc04fd6ea,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
18,barcode18_assembly,chromosome,-,-,contig_26,3940,0.527157,c8c81bedf308ff039cf7bbdeda838cbb,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
19,barcode18_assembly,chromosome,-,-,contig_27,2593,0.382568,97ad48ebd52b046e6fa2f231d4a1ddf9,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
20,barcode18_assembly,chromosome,-,-,contig_28,4855,0.548919,ddee33fd86efea80c1ac5e42753b68e1,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
21,barcode18_assembly,chromosome,-,-,contig_29,4068,0.559243,5858d2fb9f2a32a3c6e9c5ef61a87882,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
22,barcode18_assembly,chromosome,-,-,contig_3,4064,0.541585,5abbbdd7190294ee08489d43ce07e602,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
23,barcode18_assembly,chromosome,-,-,contig_4,3897,0.541699,04f6f938c84cefa3e9bddff0fed55b1d,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
24,barcode18_assembly,chromosome,-,-,contig_5,3813,0.525308,183f17d5084ca305ced7dc4c1223bdec,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
25,barcode18_assembly,chromosome,-,-,contig_6,3192,0.551692,48ef1a2f13b396800861e14f325692f5,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
26,barcode18_assembly,chromosome,-,-,contig_7,4016,0.584661,350ccdfb1efa91895b9ad566b02c2dd1,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
27,barcode18_assembly,chromosome,-,-,contig_8,3261,0.516406,57e3d30483499126c092c90db2c3d1c6,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
28,barcode18_assembly,chromosome,-,-,contig_9,2552,0.555643,5aeb0940a2b2787ca1776070c1b70ad2,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode18
0,barcode07_assembly,chromosome,-,-,contig_1,2723,0.529196,d80e0b3bfbc37f1875d13247f8d1576b,not tested,-,...,-,-,-,-,-,-,-,-,-,barcode07
1,barcode07_assembly,plasmid,AB434,AK211,contig_2,2860,0.421678,0f059eb75aa91abffd07be8ebd0872b5,not tested,Col3M,...,-,-,-,JQ776508,0.00265838,Proteus mirabilis,-,-,-,barcode07

In [22]:
merged = all_amr.merge(
    mob_all,
    left_on=["barcode", "Contig id"],
    right_on=["barcode", "contig_id"],
    how="left"
)

In [23]:
merged[["barcode", "Element symbol", "Class", "Contig id", "molecule_type"]]

     barcode Element symbol      Class  Contig id molecule_type
0  barcode07          qnrD1  QUINOLONE   contig_2       plasmid
1  barcode09           qnrD  QUINOLONE   contig_4       plasmid
2  barcode18          qnrD1  QUINOLONE  contig_20       plasmid

In [24]:
plasmid_amr = merged[
    merged["molecule_type"] == "plasmid"
]

plasmid_amr

,Protein id,Contig id,Start,Stop,Strand,Element symbol,Element name,Scope,Type,Subtype,...,mpf_type_accession(s),orit_type(s),orit_accession(s),predicted_mobility,mash_nearest_neighbor,mash_neighbor_distance,mash_neighbor_identification,repetitive_dna_id,repetitive_dna_type,filtering_reason
0,NaN,contig_2,1660,2301,-,qnrD1,quinolone resistance pentapeptide repeat prote...,core,AMR,AMR,...,-,-,-,-,JQ776508,0.00265838,Proteus mirabilis,-,-,-
1,NaN,contig_4,2146,2682,+,qnrD,QnrD family quinolone resistance pentapeptide ...,core,AMR,AMR,...,-,-,-,-,JQ776508,0.00378594,Proteus mirabilis,-,-,-
2,NaN,contig_20,919,1560,+,qnrD1,quinolone resistance pentapeptide repeat prote...,core,AMR,AMR,...,-,-,-,-,JQ776508,0.00141786,Proteus mirabilis,-,-,-